# Generated by Django 4.1.3 on 2022-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
